### PR TITLE
fix stream upload headers

### PR DESCRIPTION
**Pull request by newmaka50**
addCustomHeader not working
ensureHeader instead

Signed-off-by: newmaka50 <43097142+newmaka50@users.noreply.github.com>

### CODE REVIEW

**Comment by newmaka50** [comment]
zdfdg

**Comment by blizzz** [comment]
meh, the method name was changed in phpSPO 2.4.3

**Review by blizzz — APPROVED** [review]

**Comment by blizzz** [comment]
@newmaka50 thank you for your contribution :+1:

**Pull request merged**
