### PR TITLE
Update master php testing versions

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Review by blizzz — APPROVED** [review]

**Comment by nickvergessen** [comment]
Run ./vendor/phpunit/phpunit/phpunit -c ./tests/phpunit.xml
/home/runner/work/_temp/7daee967-9cf7-4fd5-abde-c7b457e5a402.sh: line 1: ./vendor/phpunit/phpunit/phpunit: No such file or directory
Error: Process completed with exit code 127.

**Comment by nickvergessen** [comment]
Missing composer.lock update so it's not installed?

**Comment by come-nc** [comment]
Ok it’s from 2.4.0: https://github.com/vgrem/phpSPO/releases/tag/v2.4.0

@blizzz You seem to have contributions upstream, could you look into bringing the code up to date with upstream api changes?

**Review by blizzz — APPROVED** [review]

**Comment by blizzz** [comment]
> Ok it’s from 2.4.0: https://github.com/vgrem/phpSPO/releases/tag/v2.4.0
> 
> @blizzz You seem to have contributions upstream, could you look into bringing the code up to date with upstream api changes?

It's in https://github.com/nextcloud/sharepoint/pull/62 need to finish this off

**Comment by blizzz** [comment]
@come-nc i've added another flock of commits (upon a rebase). Seems like unit tests did not run properly before? a bit weird. Anyway, green now – wanna look over them?

**Review by come-nc — APPROVED** [review]

**Comment by come-nc** [comment]
> @come-nc i've added another flock of commits (upon a rebase). Seems like unit tests did not run properly before? a bit weird. Anyway, green now – wanna look over them?

Would be better to use the phpunit workflows from nextcloud/.github but that can be done at a later, merging.

**Pull request merged**
